# Generated by Django 2.2.16 on 2022-08-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220805_1616'),
        ('reviews', '0008_auto_20220808_2039'),
    ]

    operations = [
    ]
