# Generated by Django 2.2.16 on 2022-08-10 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_merge_20220808_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
